blank_issues_enabled: false

issue_templates:
  - name: Epic
    description: A large initiative composed of smaller features and tasks.
    file: epic.yaml

  - name: Feature Request
    description: Suggest a new feature or enhancement.
    file: feature.yaml