name: Enforce Acceptance Criteria Checklist

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  enforce_acceptance_criteria:
    runs-on: ubuntu-latest
    steps:
    - name: Check Acceptance Criteria Checkboxes
      uses: actions/github-script@v7
      with:
        script: |
          const issue = context.payload.issue;
          const body = issue.body;
          const issue_number = issue.number;
          const labels = issue.labels.map(l => l.name.toLowerCase());

          async function retry(fn, retries = 3, delay = 2000) {
            for (let attempt = 0; attempt < retries; attempt++) {
              try {
                return await fn();
              } catch (err) {
                console.warn(`⚠️ Attempt ${attempt + 1} failed: ${err.message}`);
                if (attempt < retries - 1) {
                  await new Promise(res => setTimeout(res, delay * (attempt + 1)));
                } else {
                  throw err;
                }
              }
            }
          }
  
          const skipReasons = ['duplicate', 'wontfix', 'not planned', 'invalid'];
          const shouldSkip = labels.some(l => skipReasons.includes(l));
          
          const match = body.match(/#+\s*✅?\s*Acceptance Criteria\s*\n+([\s\S]+?)(\n#+|\n*$)/i);
          
          if (shouldSkip) {
            console.log(`Skipping checklist check due to label(s): ${labels.join(', ')}`);
            return;
          }
          
          if (match && match[1]) {
            const criteriaSection = match[1];
            const unchecked = criteriaSection.match(/- \[ \]/g);
          
            if (unchecked && unchecked.length > 0) {
              if (issue.state !== 'open') {
                await retry(() => github.rest.issues.update({
                  ...context.repo,
                  issue_number,
                  state: 'open'
                }));
              }
          
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number,
                body: `❌ This issue still has ${unchecked.length} unchecked acceptance criteria.\n\nPlease complete all acceptance items before closing.`
              });
          
              console.log(`Reopened issue #${issue_number} due to unchecked boxes.`);
            }
          }